<?php
$time_start = microtime(true); 

// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, 'https://docs.google.com/spreadsheets/d/1CQx93XDFRNRHN7ukcAVWH7cqKNTpfxjRbtSnXNon-yU/linkdetails?id=1CQx93XDFRNRHN7ukcAVWH7cqKNTpfxjRbtSnXNon-yU&linkurl=https%3A%2F%2Fwww.amazon.com%2Fscience-kit%2Fs%3Fk%3Dscience%2Bkit%26rh%3Dp_78%253AB07VN75JFC%26gclid%3DHDYuCjYEQGp1jXRrcGDdUiv1cRDrxM9I7nrBp1x3Pi4fxCI5FyJ_ExF%26maas%3Dmaas_adg_37F3E76B97198FA7CD670D009007A2CD_afap_abs%26ref_%3Daa_maas&token=AC4w5Vgw_AZbN94azzyKnydm8WDpqGD23w%3A1636569839100&includes_info_params=true');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');

curl_setopt($ch, CURLOPT_ENCODING, 'gzip, deflate');
 
$headers = array();
$headers[] = 'Authority: docs.google.com';
$headers[] = 'X-Build: trix_2021.43-Tue_RC06';
$headers[] = 'X-Same-Domain: 1';
$headers[] = 'X-Rel-Id: 6e9.ad6883f.s';
$headers[] = 'Sec-Ch-Ua-Mobile: ?0';
$headers[] = 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36';
$headers[] = 'Sec-Ch-Ua: \"Google Chrome\";v=\"95\", \"Chromium\";v=\"95\", \";Not A Brand\";v=\"99\"';
$headers[] = 'Sec-Ch-Ua-Platform: \"Linux\"';
$headers[] = 'Accept: */*';
$headers[] = 'X-Client-Data: CJW2yQEIprbJAQipncoBCJ+OywEI6vLLAQjv8ssBCJ75ywEI5oTMAQi1hcwBCP+FzAEIy4nMAQiyi8wBCI6NzAE=';
$headers[] = 'Sec-Fetch-Site: same-origin';
$headers[] = 'Sec-Fetch-Mode: cors';
$headers[] = 'Sec-Fetch-Dest: empty';
$headers[] = 'Referer: https://docs.google.com/spreadsheets/d/1CQx93XDFRNRHN7ukcAVWH7cqKNTpfxjRbtSnXNon-yU/edit';
$headers[] = 'Accept-Language: en-US,en;q=0.9';
$headers[] = 'Cookie: S=apps-spreadsheets=o9DU9ZXU813HQHSpxPwL6DIbWKLzJREnxKkzaOZGCvI; COMPASS=apps-spreadsheets=CjIACWuJV8dEH7M29Dzbgmwb4s5JNhtYshaoRsEHG199SZh5BHS9XghAi9tMRhwKxry1_xCkwrCMBho0AAlriVcpJS9aPjIzon7wYS16hL1F6NnFemUM0N9DFyno_Jht649eAhRcauGHsUDRu1KdSQ==; CONSENT=YES+shp.gws-20210802-0-RC1.es+FX+931; HSID=AafTnXnUwAUEI5QA5; SSID=AF_ujqJmwdclY7ZTZ; APISID=vfSxGNkvJlA3DIMw/At1c_LYLcmcKhCzQQ; SAPISID=XYbHv16g0Zo9WNhm/AmK_gU4Q-gp4GyStv; __Secure-1PAPISID=XYbHv16g0Zo9WNhm/AmK_gU4Q-gp4GyStv; __Secure-3PAPISID=XYbHv16g0Zo9WNhm/AmK_gU4Q-gp4GyStv; SEARCH_SAMESITE=CgQImpMB; SID=DgjEjWxzQeBVASWsMNTSn1sMniFsRpft3R8vdfnFM31Pfx6geAdkv5oqPxXjlH5ct0fmVA.; __Secure-1PSID=DgjEjWxzQeBVASWsMNTSn1sMniFsRpft3R8vdfnFM31Pfx6gOqLIET_ykLtHvSw_8_NGTw.; __Secure-3PSID=DgjEjWxzQeBVASWsMNTSn1sMniFsRpft3R8vdfnFM31Pfx6gdpO0875MBh_9d-NoG-o6fw.; __Secure-1PSIDCC=AJi4QfGfbx0ytKZS072-4oiZMJN0fxXY-CFXVqa9FJWWkihWVhdX7zEt50JxtmLtkJojJSyYpQ; 1P_JAR=2021-11-10-17; NID=511=XbOvBdBBB4vnQGW-tHUhEcLjkA1Vbs9zds_UpHOMwl0mmCwF28Z6OkSDn1_bbBzscwjFRGXsBFlg6m2TBDGu9Dd5SPavpTk0VQhs_ss0BviM7Jw3kBMhQtAJpG8eo6ZMWSx31IQP2LPl8czmUTSfPOwkao4dCLMX3kplr1AxbpGlkgXL6D8ClaKpiEnEh0bQbvCywhPdRhetTtA78fEHmjH7tSgFkWw6YxaEiMdMfvi-olIoQ5yQjRoOD6ec; SIDCC=AJi4QfE2Fhgill6xxYfzjFlifbj6XqG1EehdkE0wIaOZS_zU3hAh1W-Nmf9m04avgNAE9UzvIYo; __Secure-3PSIDCC=AJi4QfEGlghWJYHteUTcKL_GvBiEUykVs_xVXVoEKp01JU3yK6yfrLdshJx45arKeSAiRLF1Xw';
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);
if (curl_errno($ch)) {
    //echo 'Error:' . curl_error($ch);
	exit;
}
curl_close($ch);

//echo $result .'<br><br><br>' ;


$array=explode(",",$result);

if(count($array)!=0)
{
	foreach($array as $value)
	{

		//echo $value.'<br>' ;
		if (strpos($value, 'google.com') !== false) {
			//echo '++<br>' ;
			$dd = str_replace('"',"",$value);
			break ;
		}

	}
}
//echo $dd ;
$json = sprintf('"%s"',$dd); # build json string
$utf8_str = json_decode ( $json, true ); # json decode
//echo $utf8_str ;	
	
$time_end = microtime(true);

//dividing with 60 will give the execution time in minutes otherwise seconds
$execution_time = ($time_end - $time_start);

//execution time of the script
//echo '<br><br><b>Total Execution Time:</b> '.number_format((float) $execution_time, 10).' Seconds <br>';
// if you get weird results, use number_format((float) $execution_time, 10) 	
header('Content-Type: application/json; charset=utf-8');
//echo json_encode($data);

echo "{'url' : ".$utf8_str."}" ;

?>


